site_name: jcktch/pkb
site_url: https://mydomain.org/mysite
repo_url: https://github.com/jcktch/pkb.git
repo_name: jcktch/pkb

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  language: fr
  features:
    - navigation.sections
  icon:
    logo: fontawesome/solid/terminal
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Basculer en mode sombre

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Basculer en mode clair

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences


nav:
  - Accueil: index.md

  - ENVIRONMENTS VULNÉRABLES:
      - Introduction: reseau/index.md
      - Protocoles:
          - TCP/IP:
              - Overview: reseau/protocoles/tcp-ip/page-01.md
          - Sécurité:
              - Update Manager: reseau/protocoles/securite/page-01.md
          - Cisco :
              - mainsail.cfg: reseau/protocoles/cisco/page-01.md

  - Programmation:
      - Introduction: programmation/index.md
      - C:
          - Variables:
              - Overview: programmation/C/variables/page-01.md
          - Conditions:
              - Update Manager: programmation/C/conditions/page-01.md
          - Boucles:
              - mainsail.cfg: programmation/C/boucles/page-01.md